/*
 * Copyright (c) 2022 Craig Watt
 *
 * Contact: craig@webrefine.co.uk
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "m_mezzanine_struct.h"

static void o_create_custom_folders_if_missing(char *workspace_root, cf_node_t *cf_head) {
  cf_node_t *current = cf_head;

  while(current != NULL) {
    char *custom_folder_path = NULL;

    if(current->folder_name == NULL || current->folder_name[0] == '\0') {
      current = current->next;
      continue;
    }

    custom_folder_path = utils_combine_to_full_path(workspace_root, current->folder_name);
    if(!utils_does_folder_exist(custom_folder_path))
      utils_create_folder(custom_folder_path);

    if(!utils_does_folder_exist(custom_folder_path)) {
      printf("MEZZANINE MAJOR ERROR: vfo could not create required custom folder %s\n", custom_folder_path);
      free(custom_folder_path);
      exit(EXIT_FAILURE);
    }

    free(custom_folder_path);
    current = current->next;
  }
}

static char* o_get_or_create_original_workspace(char *original_root,
                                                const char *workspace_name,
                                                cf_node_t *cf_head) {
  char *workspace_path = malloc(BUFSIZ);
  strcpy(workspace_path, original_root);
  strcat(workspace_path, "/");
  strcat(workspace_path, workspace_name);

  if(!utils_does_folder_exist(workspace_path)) {
    printf("MEZZANINE ALERT: %s missing in %s, preparing it now.\n", workspace_name, original_root);
    utils_ask_user_for_permission_to_create_a_folder(workspace_path);
    utils_create_folder(workspace_path);
  }

  if(!utils_does_folder_exist(workspace_path)) {
    printf("MEZZANINE MAJOR ERROR: vfo could not create %s and it does not exist.\n", workspace_path);
    exit(EXIT_FAILURE);
  }

  o_create_custom_folders_if_missing(workspace_path, cf_head);
  return workspace_path;
}

original_t* original_create_new_struct(config_t *config) {
  original_t *result = malloc(sizeof(original_t));
  //point to relevant param config variables
  result->root = config->svc->original_location;
  //this simply points to cf_head generated by config.
  result->cf_head = config->cf_head;
  //needs to be verified
  result->start = o_create_start(result->root);
  //needs to be verified
  result->unable_to_process = o_create_unable_to_process(result->root);

  result->mkv_extension = ".mkv";
  result->mp4_extension = ".mp4";
  result->m2ts_extension = ".m2ts";
  //ensure mezzanine extension workspaces exist and are custom-folder ready
  result->mkv_original = o_get_mkv_original_if_it_exists(result->root, result->cf_head);
  result->mp4_original = o_get_mp4_original_if_it_exists(result->root, result->cf_head);
  result->m2ts_original = o_get_m2ts_original_if_it_exists(result->root, result->cf_head);
  return result;
}

char* o_create_start(char *original_root) {
  //create
  char *tmp_original_start = malloc(BUFSIZ);
  strcpy(tmp_original_start, original_root);
  strcat(tmp_original_start, "/start");
  if(utils_does_folder_exist(tmp_original_start))
    return tmp_original_start;

  printf("MEZZANINE INFO: /start folder not found in %s. Using mezzanine root as active workspace.\n", original_root);
  free(tmp_original_start);
  return original_root;
}

char* o_create_unable_to_process(char *original_root) {
  //create
  char *tmp_original_unable_to_process = malloc(BUFSIZ);
  strcpy(tmp_original_unable_to_process, original_root);
  strcat(tmp_original_unable_to_process, "/unable_to_process");
  //verify
  if(!utils_does_folder_exist(tmp_original_unable_to_process)) {
    printf("MEZZANINE WARNING: vfo could not find an essential /unable_to_process folder in %s\n",original_root);
    utils_ask_user_for_permission_to_create_a_folder(tmp_original_unable_to_process);
    utils_create_folder(tmp_original_unable_to_process);
    if(!utils_does_folder_exist(tmp_original_unable_to_process)) {
      printf("MEZZANINE MAJOR ERROR: vfo could not create %s & it does not exist MEZZANINE MAJOR ERROR\n", tmp_original_unable_to_process);
      exit(EXIT_FAILURE);
    }
  }
  return tmp_original_unable_to_process;
}

char* o_get_mkv_original_if_it_exists(char *original_root, cf_node_t *cf_head) {
  return o_get_or_create_original_workspace(original_root, "mkv_original", cf_head);
}

char* o_get_mp4_original_if_it_exists(char *original_root, cf_node_t *cf_head) {
  return o_get_or_create_original_workspace(original_root, "mp4_original", cf_head);
}

char* o_get_m2ts_original_if_it_exists(char *original_root, cf_node_t *cf_head) {
  return o_get_or_create_original_workspace(original_root, "m2ts_original", cf_head);
}
