name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
          
    - name: Build using make
      run: make
      
    - name: Release
      uses: softprops/action-gh-release@v0.1.15
#       if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        body: "place vfo & vfo_config.conf files into /usr/local/bin/ (DEV: need to change make install procedure for myself locally so conf isn't in a folder)"
        files: |
          bin/vfo
          src/vfo_config.conf
