name: Test

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: test brew is installed
      run: brew -v

    - name: test cmocka library is installed
      run: brew install cmocka
    
    - name: run make tests
      run: make tests

    - name: run make clean_tests
      run: make clean_tests
