name: Validate (PR + main)

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  validate:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: verify brew is installed
        run: brew -v

      - name: install cmocka
        run: brew install cmocka

      - name: build application
        run: make all

      - name: run tests
        run: make tests

      - name: clean test artifacts
        if: always()
        run: make clean_tests

      - name: clean build artifacts
        if: always()
        run: make clean
