name: Makefile CI - vfo test workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: test brew is installed
      run: brew -v

    - name: test cmocka library is installed
      run: brew install cmocka
    
    - name: run make tests
      run: make

    - name: run ls -la
      run: ls -la

    - name : run ls -la test/lib
      run: ls -la test/lib
      
    - name: run make clean_tests
      run: make clean_tests
