name: Makefile CI - vfo test workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: test brew is installed
      run: brew -v

    - name: test cmocka library is installed
      run: brew install cmocka
    
    - name: Install dependencies
      run: make
    
    - name: make tests
      run: make tests
